/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/dataconnect/v1/data.proto

package com.google.events.firebase.dataconnect.v1;

/**
 *
 *
 * <pre>
 * A data source that backs Firebase Data Connect services.
 * </pre>
 *
 * Protobuf type {@code google.events.firebase.dataconnect.v1.Datasource}
 */
public final class Datasource extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.events.firebase.dataconnect.v1.Datasource)
    DatasourceOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use Datasource.newBuilder() to construct.
  private Datasource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Datasource() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new Datasource();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.events.firebase.dataconnect.v1.Data
        .internal_static_google_events_firebase_dataconnect_v1_Datasource_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.events.firebase.dataconnect.v1.Data
        .internal_static_google_events_firebase_dataconnect_v1_Datasource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.events.firebase.dataconnect.v1.Datasource.class,
            com.google.events.firebase.dataconnect.v1.Datasource.Builder.class);
  }

  private int configurationCase_ = 0;
  private java.lang.Object configuration_;

  public enum ConfigurationCase
      implements
          com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    POSTGRESQL(2),
    CONFIGURATION_NOT_SET(0);
    private final int value;

    private ConfigurationCase(int value) {
      this.value = value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConfigurationCase valueOf(int value) {
      return forNumber(value);
    }

    public static ConfigurationCase forNumber(int value) {
      switch (value) {
        case 2:
          return POSTGRESQL;
        case 0:
          return CONFIGURATION_NOT_SET;
        default:
          return null;
      }
    }

    public int getNumber() {
      return this.value;
    }
  };

  public ConfigurationCase getConfigurationCase() {
    return ConfigurationCase.forNumber(configurationCase_);
  }

  public static final int POSTGRESQL_FIELD_NUMBER = 2;

  /**
   *
   *
   * <pre>
   * PostgreSQL configurations.
   * </pre>
   *
   * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
   *
   * @return Whether the postgresql field is set.
   */
  @java.lang.Override
  public boolean hasPostgresql() {
    return configurationCase_ == 2;
  }

  /**
   *
   *
   * <pre>
   * PostgreSQL configurations.
   * </pre>
   *
   * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
   *
   * @return The postgresql.
   */
  @java.lang.Override
  public com.google.events.firebase.dataconnect.v1.PostgreSql getPostgresql() {
    if (configurationCase_ == 2) {
      return (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_;
    }
    return com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
  }

  /**
   *
   *
   * <pre>
   * PostgreSQL configurations.
   * </pre>
   *
   * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
   */
  @java.lang.Override
  public com.google.events.firebase.dataconnect.v1.PostgreSqlOrBuilder getPostgresqlOrBuilder() {
    if (configurationCase_ == 2) {
      return (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_;
    }
    return com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (configurationCase_ == 2) {
      output.writeMessage(2, (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (configurationCase_ == 2) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              2, (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.events.firebase.dataconnect.v1.Datasource)) {
      return super.equals(obj);
    }
    com.google.events.firebase.dataconnect.v1.Datasource other =
        (com.google.events.firebase.dataconnect.v1.Datasource) obj;

    if (!getConfigurationCase().equals(other.getConfigurationCase())) return false;
    switch (configurationCase_) {
      case 2:
        if (!getPostgresql().equals(other.getPostgresql())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (configurationCase_) {
      case 2:
        hash = (37 * hash) + POSTGRESQL_FIELD_NUMBER;
        hash = (53 * hash) + getPostgresql().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.events.firebase.dataconnect.v1.Datasource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   *
   *
   * <pre>
   * A data source that backs Firebase Data Connect services.
   * </pre>
   *
   * Protobuf type {@code google.events.firebase.dataconnect.v1.Datasource}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.events.firebase.dataconnect.v1.Datasource)
      com.google.events.firebase.dataconnect.v1.DatasourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.events.firebase.dataconnect.v1.Data
          .internal_static_google_events_firebase_dataconnect_v1_Datasource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.events.firebase.dataconnect.v1.Data
          .internal_static_google_events_firebase_dataconnect_v1_Datasource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.events.firebase.dataconnect.v1.Datasource.class,
              com.google.events.firebase.dataconnect.v1.Datasource.Builder.class);
    }

    // Construct using com.google.events.firebase.dataconnect.v1.Datasource.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (postgresqlBuilder_ != null) {
        postgresqlBuilder_.clear();
      }
      configurationCase_ = 0;
      configuration_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.events.firebase.dataconnect.v1.Data
          .internal_static_google_events_firebase_dataconnect_v1_Datasource_descriptor;
    }

    @java.lang.Override
    public com.google.events.firebase.dataconnect.v1.Datasource getDefaultInstanceForType() {
      return com.google.events.firebase.dataconnect.v1.Datasource.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.events.firebase.dataconnect.v1.Datasource build() {
      com.google.events.firebase.dataconnect.v1.Datasource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.events.firebase.dataconnect.v1.Datasource buildPartial() {
      com.google.events.firebase.dataconnect.v1.Datasource result =
          new com.google.events.firebase.dataconnect.v1.Datasource(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.events.firebase.dataconnect.v1.Datasource result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.events.firebase.dataconnect.v1.Datasource result) {
      result.configurationCase_ = configurationCase_;
      result.configuration_ = this.configuration_;
      if (configurationCase_ == 2 && postgresqlBuilder_ != null) {
        result.configuration_ = postgresqlBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.events.firebase.dataconnect.v1.Datasource) {
        return mergeFrom((com.google.events.firebase.dataconnect.v1.Datasource) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.events.firebase.dataconnect.v1.Datasource other) {
      if (other == com.google.events.firebase.dataconnect.v1.Datasource.getDefaultInstance())
        return this;
      switch (other.getConfigurationCase()) {
        case POSTGRESQL:
          {
            mergePostgresql(other.getPostgresql());
            break;
          }
        case CONFIGURATION_NOT_SET:
          {
            break;
          }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18:
              {
                input.readMessage(getPostgresqlFieldBuilder().getBuilder(), extensionRegistry);
                configurationCase_ = 2;
                break;
              } // case 18
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int configurationCase_ = 0;
    private java.lang.Object configuration_;

    public ConfigurationCase getConfigurationCase() {
      return ConfigurationCase.forNumber(configurationCase_);
    }

    public Builder clearConfiguration() {
      configurationCase_ = 0;
      configuration_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.events.firebase.dataconnect.v1.PostgreSql,
            com.google.events.firebase.dataconnect.v1.PostgreSql.Builder,
            com.google.events.firebase.dataconnect.v1.PostgreSqlOrBuilder>
        postgresqlBuilder_;

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     *
     * @return Whether the postgresql field is set.
     */
    @java.lang.Override
    public boolean hasPostgresql() {
      return configurationCase_ == 2;
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     *
     * @return The postgresql.
     */
    @java.lang.Override
    public com.google.events.firebase.dataconnect.v1.PostgreSql getPostgresql() {
      if (postgresqlBuilder_ == null) {
        if (configurationCase_ == 2) {
          return (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_;
        }
        return com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
      } else {
        if (configurationCase_ == 2) {
          return postgresqlBuilder_.getMessage();
        }
        return com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
      }
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    public Builder setPostgresql(com.google.events.firebase.dataconnect.v1.PostgreSql value) {
      if (postgresqlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        configuration_ = value;
        onChanged();
      } else {
        postgresqlBuilder_.setMessage(value);
      }
      configurationCase_ = 2;
      return this;
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    public Builder setPostgresql(
        com.google.events.firebase.dataconnect.v1.PostgreSql.Builder builderForValue) {
      if (postgresqlBuilder_ == null) {
        configuration_ = builderForValue.build();
        onChanged();
      } else {
        postgresqlBuilder_.setMessage(builderForValue.build());
      }
      configurationCase_ = 2;
      return this;
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    public Builder mergePostgresql(com.google.events.firebase.dataconnect.v1.PostgreSql value) {
      if (postgresqlBuilder_ == null) {
        if (configurationCase_ == 2
            && configuration_
                != com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance()) {
          configuration_ =
              com.google.events.firebase.dataconnect.v1.PostgreSql.newBuilder(
                      (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          configuration_ = value;
        }
        onChanged();
      } else {
        if (configurationCase_ == 2) {
          postgresqlBuilder_.mergeFrom(value);
        } else {
          postgresqlBuilder_.setMessage(value);
        }
      }
      configurationCase_ = 2;
      return this;
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    public Builder clearPostgresql() {
      if (postgresqlBuilder_ == null) {
        if (configurationCase_ == 2) {
          configurationCase_ = 0;
          configuration_ = null;
          onChanged();
        }
      } else {
        if (configurationCase_ == 2) {
          configurationCase_ = 0;
          configuration_ = null;
        }
        postgresqlBuilder_.clear();
      }
      return this;
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    public com.google.events.firebase.dataconnect.v1.PostgreSql.Builder getPostgresqlBuilder() {
      return getPostgresqlFieldBuilder().getBuilder();
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    @java.lang.Override
    public com.google.events.firebase.dataconnect.v1.PostgreSqlOrBuilder getPostgresqlOrBuilder() {
      if ((configurationCase_ == 2) && (postgresqlBuilder_ != null)) {
        return postgresqlBuilder_.getMessageOrBuilder();
      } else {
        if (configurationCase_ == 2) {
          return (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_;
        }
        return com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
      }
    }

    /**
     *
     *
     * <pre>
     * PostgreSQL configurations.
     * </pre>
     *
     * <code>.google.events.firebase.dataconnect.v1.PostgreSql postgresql = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.events.firebase.dataconnect.v1.PostgreSql,
            com.google.events.firebase.dataconnect.v1.PostgreSql.Builder,
            com.google.events.firebase.dataconnect.v1.PostgreSqlOrBuilder>
        getPostgresqlFieldBuilder() {
      if (postgresqlBuilder_ == null) {
        if (!(configurationCase_ == 2)) {
          configuration_ =
              com.google.events.firebase.dataconnect.v1.PostgreSql.getDefaultInstance();
        }
        postgresqlBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.events.firebase.dataconnect.v1.PostgreSql,
                com.google.events.firebase.dataconnect.v1.PostgreSql.Builder,
                com.google.events.firebase.dataconnect.v1.PostgreSqlOrBuilder>(
                (com.google.events.firebase.dataconnect.v1.PostgreSql) configuration_,
                getParentForChildren(),
                isClean());
        configuration_ = null;
      }
      configurationCase_ = 2;
      onChanged();
      return postgresqlBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.events.firebase.dataconnect.v1.Datasource)
  }

  // @@protoc_insertion_point(class_scope:google.events.firebase.dataconnect.v1.Datasource)
  private static final com.google.events.firebase.dataconnect.v1.Datasource DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.events.firebase.dataconnect.v1.Datasource();
  }

  public static com.google.events.firebase.dataconnect.v1.Datasource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Datasource> PARSER =
      new com.google.protobuf.AbstractParser<Datasource>() {
        @java.lang.Override
        public Datasource parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<Datasource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Datasource> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.events.firebase.dataconnect.v1.Datasource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
