/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/dataconnect/v1/data.proto

package com.google.events.firebase.dataconnect.v1;

public interface SourceOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.events.firebase.dataconnect.v1.Source)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The files that comprise the source set.
   * </pre>
   *
   * <code>repeated .google.events.firebase.dataconnect.v1.File files = 1;</code>
   */
  java.util.List<com.google.events.firebase.dataconnect.v1.File> getFilesList();

  /**
   *
   *
   * <pre>
   * Required. The files that comprise the source set.
   * </pre>
   *
   * <code>repeated .google.events.firebase.dataconnect.v1.File files = 1;</code>
   */
  com.google.events.firebase.dataconnect.v1.File getFiles(int index);

  /**
   *
   *
   * <pre>
   * Required. The files that comprise the source set.
   * </pre>
   *
   * <code>repeated .google.events.firebase.dataconnect.v1.File files = 1;</code>
   */
  int getFilesCount();

  /**
   *
   *
   * <pre>
   * Required. The files that comprise the source set.
   * </pre>
   *
   * <code>repeated .google.events.firebase.dataconnect.v1.File files = 1;</code>
   */
  java.util.List<? extends com.google.events.firebase.dataconnect.v1.FileOrBuilder>
      getFilesOrBuilderList();

  /**
   *
   *
   * <pre>
   * Required. The files that comprise the source set.
   * </pre>
   *
   * <code>repeated .google.events.firebase.dataconnect.v1.File files = 1;</code>
   */
  com.google.events.firebase.dataconnect.v1.FileOrBuilder getFilesOrBuilder(int index);
}
