// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/testlab/v1/data.proto

package com.google.events.firebase.testlab.v1;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.events.firebase.testlab.v1.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Client name, such as "gcloud".
   * </pre>
   *
   * <code>string client = 1;</code>
   * @return The client.
   */
  java.lang.String getClient();
  /**
   * <pre>
   * Client name, such as "gcloud".
   * </pre>
   *
   * <code>string client = 1;</code>
   * @return The bytes for client.
   */
  com.google.protobuf.ByteString
      getClientBytes();

  /**
   * <pre>
   * Map of detailed information about the client.
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 2;</code>
   */
  int getDetailsCount();
  /**
   * <pre>
   * Map of detailed information about the client.
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 2;</code>
   */
  boolean containsDetails(
      java.lang.String key);
  /**
   * Use {@link #getDetailsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDetails();
  /**
   * <pre>
   * Map of detailed information about the client.
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDetailsMap();
  /**
   * <pre>
   * Map of detailed information about the client.
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 2;</code>
   */

  /* nullable */
java.lang.String getDetailsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * Map of detailed information about the client.
   * </pre>
   *
   * <code>map&lt;string, string&gt; details = 2;</code>
   */

  java.lang.String getDetailsOrThrow(
      java.lang.String key);
}
