allowedCopyrightHolders:
  - "Google LLC"
  - "Google Inc."
allowedLicenses:
  - "Apache-2.0"
sourceFileExtensions:
  - "yaml"
  - "yml"
  - "sh"
  - "proto"
  - "java"
ignoreFiles:
  - ".github/release-please.yml"
  - ".github/release-trigger.yml"
  - ".github/header-checker-lint.yml"
  - ".github/sync-repo-settings.yaml"
  - ".kokoro/**"