// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/cloudbuild/v1/data.proto

package com.google.events.cloud.cloudbuild.v1;

public final class Data {
    private Data() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_SubstitutionsEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_SubstitutionsEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_TimingEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_TimingEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Source_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Source_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_StorageSource_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_StorageSource_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_RepoSource_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_RepoSource_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_RepoSource_SubstitutionsEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuildStep_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuildStep_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Volume_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Volume_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Results_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Results_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuiltImage_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuiltImage_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Artifacts_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Artifacts_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Artifacts_ArtifactObjects_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_TimeSpan_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_TimeSpan_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_FileHashes_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_FileHashes_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Hash_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Hash_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Secret_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Secret_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_Secret_SecretEnvEntry_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_Secret_SecretEnvEntry_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_google_events_cloud_cloudbuild_v1_BuildOptions_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_google_events_cloud_cloudbuild_v1_BuildOptions_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n,google/events/cloud/cloudbuild/v1/data"
                + ".proto\022!google.events.cloud.cloudbuild.v" + "1\032\036google/protobuf/duration.proto\032\037googl"
                + "e/protobuf/timestamp.proto\"\354\n\n\016BuildEven"
                + "tData\022\n\n\002id\030\001 \001(\t\022\022\n\nproject_id\030\020 \001(\t\022H\n"
                + "\006status\030\002 \001(\01628.google.events.cloud.clou"
                + "dbuild.v1.BuildEventData.Status\022\025\n\rstatu"
                + "s_detail\030\030 \001(\t\0229\n\006source\030\003 \001(\0132).google."
                + "events.cloud.cloudbuild.v1.Source\022;\n\005ste"
                + "ps\030\013 \003(\0132,.google.events.cloud.cloudbuil"
                + "d.v1.BuildStep\022;\n\007results\030\n \001(\0132*.google"
                + ".events.cloud.cloudbuild.v1.Results\022/\n\013c"
                + "reate_time\030\006 \001(\0132\032.google.protobuf.Times"
                + "tamp\022.\n\nstart_time\030\007 \001(\0132\032.google.protob"
                + "uf.Timestamp\022/\n\013finish_time\030\010 \001(\0132\032.goog"
                + "le.protobuf.Timestamp\022*\n\007timeout\030\014 \001(\0132\031"
                + ".google.protobuf.Duration\022\016\n\006images\030\r \003("
                + "\t\022,\n\tqueue_ttl\030( \001(\0132\031.google.protobuf.D"
                + "uration\022?\n\tartifacts\030% \001(\0132,.google.even"
                + "ts.cloud.cloudbuild.v1.Artifacts\022\023\n\013logs"
                + "_bucket\030\023 \001(\t\022N\n\021source_provenance\030\025 \001(\013"
                + "23.google.events.cloud.cloudbuild.v1.Sou"
                + "rceProvenance\022\030\n\020build_trigger_id\030\026 \001(\t\022"
                + "@\n\007options\030\027 \001(\0132/.google.events.cloud.c"
                + "loudbuild.v1.BuildOptions\022\017\n\007log_url\030\031 \001"
                + "(\t\022[\n\rsubstitutions\030\035 \003(\0132D.google.event"
                + "s.cloud.cloudbuild.v1.BuildEventData.Sub"
                + "stitutionsEntry\022\014\n\004tags\030\037 \003(\t\022:\n\007secrets"
                + "\030  \003(\0132).google.events.cloud.cloudbuild."
                + "v1.Secret\022M\n\006timing\030! \003(\0132=.google.event"
                + "s.cloud.cloudbuild.v1.BuildEventData.Tim"
                + "ingEntry\0324\n\022SubstitutionsEntry\022\013\n\003key\030\001 "
                + "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032Z\n\013TimingEntry\022\013\n"
                + "\003key\030\001 \001(\t\022:\n\005value\030\002 \001(\0132+.google.event"
                + "s.cloud.cloudbuild.v1.TimeSpan:\0028\001\"\214\001\n\006S"
                + "tatus\022\022\n\016STATUS_UNKNOWN\020\000\022\n\n\006QUEUED\020\001\022\013\n"
                + "\007WORKING\020\002\022\013\n\007SUCCESS\020\003\022\013\n\007FAILURE\020\004\022\022\n\016"
                + "INTERNAL_ERROR\020\005\022\013\n\007TIMEOUT\020\006\022\r\n\tCANCELL"
                + "ED\020\007\022\013\n\007EXPIRED\020\t\"\244\001\n\006Source\022J\n\016storage_"
                + "source\030\002 \001(\01320.google.events.cloud.cloud"
                + "build.v1.StorageSourceH\000\022D\n\013repo_source\030"
                + "\003 \001(\0132-.google.events.cloud.cloudbuild.v"
                + "1.RepoSourceH\000B\010\n\006source\"C\n\rStorageSourc"
                + "e\022\016\n\006bucket\030\001 \001(\t\022\016\n\006object\030\002 \001(\t\022\022\n\ngen"
                + "eration\030\003 \001(\003\"\262\002\n\nRepoSource\022\022\n\nproject_"
                + "id\030\001 \001(\t\022\021\n\trepo_name\030\002 \001(\t\022\025\n\013branch_na"
                + "me\030\003 \001(\tH\000\022\022\n\010tag_name\030\004 \001(\tH\000\022\024\n\ncommit"
                + "_sha\030\005 \001(\tH\000\022\013\n\003dir\030\007 \001(\t\022\024\n\014invert_rege"
                + "x\030\010 \001(\010\022W\n\rsubstitutions\030\t \003(\0132@.google."
                + "events.cloud.cloudbuild.v1.RepoSource.Su" + "bstitutionsEntry\0324\n\022SubstitutionsEntry\022\013"
                + "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\n\n\010revisi"
                + "on\"\270\003\n\tBuildStep\022\014\n\004name\030\001 \001(\t\022\013\n\003env\030\002 "
                + "\003(\t\022\014\n\004args\030\003 \003(\t\022\013\n\003dir\030\004 \001(\t\022\n\n\002id\030\005 \001"
                + "(\t\022\020\n\010wait_for\030\006 \003(\t\022\022\n\nentrypoint\030\007 \001(\t"
                + "\022\022\n\nsecret_env\030\010 \003(\t\022:\n\007volumes\030\t \003(\0132)."
                + "google.events.cloud.cloudbuild.v1.Volume"
                + "\022;\n\006timing\030\n \001(\0132+.google.events.cloud.c"
                + "loudbuild.v1.TimeSpan\022@\n\013pull_timing\030\r \001"
                + "(\0132+.google.events.cloud.cloudbuild.v1.T"
                + "imeSpan\022*\n\007timeout\030\013 \001(\0132\031.google.protob"
                + "uf.Duration\022H\n\006status\030\014 \001(\01628.google.eve"
                + "nts.cloud.cloudbuild.v1.BuildEventData.S"
                + "tatus\"$\n\006Volume\022\014\n\004name\030\001 \001(\t\022\014\n\004path\030\002 "
                + "\001(\t\"\367\001\n\007Results\022=\n\006images\030\002 \003(\0132-.google"
                + ".events.cloud.cloudbuild.v1.BuiltImage\022\031"
                + "\n\021build_step_images\030\003 \003(\t\022\031\n\021artifact_ma"
                + "nifest\030\004 \001(\t\022\025\n\rnum_artifacts\030\005 \001(\003\022\032\n\022b"
                + "uild_step_outputs\030\006 \003(\014\022D\n\017artifact_timi"
                + "ng\030\007 \001(\0132+.google.events.cloud.cloudbuil"
                + "d.v1.TimeSpan\"l\n\nBuiltImage\022\014\n\004name\030\001 \001("
                + "\t\022\016\n\006digest\030\003 \001(\t\022@\n\013push_timing\030\004 \001(\0132+"
                + ".google.events.cloud.cloudbuild.v1.TimeS"
                + "pan\"\333\001\n\tArtifacts\022\016\n\006images\030\001 \003(\t\022M\n\007obj"
                + "ects\030\002 \001(\0132<.google.events.cloud.cloudbu"
                + "ild.v1.Artifacts.ArtifactObjects\032o\n\017Arti"
                + "factObjects\022\020\n\010location\030\001 \001(\t\022\r\n\005paths\030\002"
                + " \003(\t\022;\n\006timing\030\003 \001(\0132+.google.events.clo"
                + "ud.cloudbuild.v1.TimeSpan\"h\n\010TimeSpan\022.\n"
                + "\nstart_time\030\001 \001(\0132\032.google.protobuf.Time"
                + "stamp\022,\n\010end_time\030\002 \001(\0132\032.google.protobu"
                + "f.Timestamp\"\356\002\n\020SourceProvenance\022Q\n\027reso"
                + "lved_storage_source\030\003 \001(\01320.google.event"
                + "s.cloud.cloudbuild.v1.StorageSource\022K\n\024r"
                + "esolved_repo_source\030\006 \001(\0132-.google.event"
                + "s.cloud.cloudbuild.v1.RepoSource\022X\n\013file"
                + "_hashes\030\004 \003(\0132C.google.events.cloud.clou" + "dbuild.v1.SourceProvenance.FileHashesEnt"
                + "ry\032`\n\017FileHashesEntry\022\013\n\003key\030\001 \001(\t\022<\n\005va"
                + "lue\030\002 \001(\0132-.google.events.cloud.cloudbui"
                + "ld.v1.FileHashes:\0028\001\"H\n\nFileHashes\022:\n\tfi"
                + "le_hash\030\001 \003(\0132\'.google.events.cloud.clou"
                + "dbuild.v1.Hash\"\200\001\n\004Hash\022>\n\004type\030\001 \001(\01620."
                + "google.events.cloud.cloudbuild.v1.Hash.H"
                + "ashType\022\r\n\005value\030\002 \001(\014\")\n\010HashType\022\010\n\004NO"
                + "NE\020\000\022\n\n\006SHA256\020\001\022\007\n\003MD5\020\002\"\236\001\n\006Secret\022\024\n\014"
                + "kms_key_name\030\001 \001(\t\022L\n\nsecret_env\030\003 \003(\01328"
                + ".google.events.cloud.cloudbuild.v1.Secre"
                + "t.SecretEnvEntry\0320\n\016SecretEnvEntry\022\013\n\003ke"
                + "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001\"\342\007\n\014BuildOpti"
                + "ons\022P\n\026source_provenance_hash\030\001 \003(\01620.go"
                + "ogle.events.cloud.cloudbuild.v1.Hash.Has"
                + "hType\022]\n\027requested_verify_option\030\002 \001(\0162<"
                + ".google.events.cloud.cloudbuild.v1.Build"
                + "Options.VerifyOption\022Q\n\014machine_type\030\003 \001"
                + "(\0162;.google.events.cloud.cloudbuild.v1.B"
                + "uildOptions.MachineType\022\024\n\014disk_size_gb\030"
                + "\006 \001(\003\022_\n\023substitution_option\030\004 \001(\0162B.goo"
                + "gle.events.cloud.cloudbuild.v1.BuildOpti" + "ons.SubstitutionOption\022`\n\024log_streaming_"
                + "option\030\005 \001(\0162B.google.events.cloud.cloud" + "build.v1.BuildOptions.LogStreamingOption"
                + "\022\023\n\013worker_pool\030\007 \001(\t\022L\n\007logging\030\013 \001(\0162;"
                + ".google.events.cloud.cloudbuild.v1.Build"
                + "Options.LoggingMode\022\013\n\003env\030\014 \003(\t\022\022\n\nsecr"
                + "et_env\030\r \003(\t\022:\n\007volumes\030\016 \003(\0132).google.e"
                + "vents.cloud.cloudbuild.v1.Volume\".\n\014Veri"
                + "fyOption\022\020\n\014NOT_VERIFIED\020\000\022\014\n\010VERIFIED\020\001"
                + "\"C\n\013MachineType\022\017\n\013UNSPECIFIED\020\000\022\020\n\014N1_H"
                + "IGHCPU_8\020\001\022\021\n\rN1_HIGHCPU_32\020\002\"5\n\022Substit"
                + "utionOption\022\016\n\nMUST_MATCH\020\000\022\017\n\013ALLOW_LOO"
                + "SE\020\001\"G\n\022LogStreamingOption\022\022\n\016STREAM_DEF"
                + "AULT\020\000\022\r\n\tSTREAM_ON\020\001\022\016\n\nSTREAM_OFF\020\002\"@\n"
                + "\013LoggingMode\022\027\n\023LOGGING_UNSPECIFIED\020\000\022\n\n"
                + "\006LEGACY\020\001\022\014\n\010GCS_ONLY\020\002BV\n%com.google.ev"
                + "ents.cloud.cloudbuild.v1P\001\252\002*Google.Even" + "ts.Protobuf.Cloud.CloudBuild.V1b\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                        com.google.protobuf.DurationProto.getDescriptor(),
                        com.google.protobuf.TimestampProto.getDescriptor(), });
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_descriptor = getDescriptor().getMessageTypes()
                .get(0);
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_descriptor,
                new java.lang.String[] { "Id", "ProjectId", "Status", "StatusDetail", "Source", "Steps", "Results",
                        "CreateTime", "StartTime", "FinishTime", "Timeout", "Images", "QueueTtl", "Artifacts",
                        "LogsBucket", "SourceProvenance", "BuildTriggerId", "Options", "LogUrl", "Substitutions",
                        "Tags", "Secrets", "Timing", });
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_SubstitutionsEntry_descriptor = internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_descriptor
                .getNestedTypes().get(0);
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_SubstitutionsEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_SubstitutionsEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_TimingEntry_descriptor = internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_descriptor
                .getNestedTypes().get(1);
        internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_TimingEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuildEventData_TimingEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_Source_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_google_events_cloud_cloudbuild_v1_Source_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Source_descriptor,
                new java.lang.String[] { "StorageSource", "RepoSource", "Source", });
        internal_static_google_events_cloud_cloudbuild_v1_StorageSource_descriptor = getDescriptor().getMessageTypes()
                .get(2);
        internal_static_google_events_cloud_cloudbuild_v1_StorageSource_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_StorageSource_descriptor,
                new java.lang.String[] { "Bucket", "Object", "Generation", });
        internal_static_google_events_cloud_cloudbuild_v1_RepoSource_descriptor = getDescriptor().getMessageTypes()
                .get(3);
        internal_static_google_events_cloud_cloudbuild_v1_RepoSource_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_RepoSource_descriptor,
                new java.lang.String[] { "ProjectId", "RepoName", "BranchName", "TagName", "CommitSha", "Dir",
                        "InvertRegex", "Substitutions", "Revision", });
        internal_static_google_events_cloud_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor = internal_static_google_events_cloud_cloudbuild_v1_RepoSource_descriptor
                .getNestedTypes().get(0);
        internal_static_google_events_cloud_cloudbuild_v1_RepoSource_SubstitutionsEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_RepoSource_SubstitutionsEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_BuildStep_descriptor = getDescriptor().getMessageTypes()
                .get(4);
        internal_static_google_events_cloud_cloudbuild_v1_BuildStep_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuildStep_descriptor,
                new java.lang.String[] { "Name", "Env", "Args", "Dir", "Id", "WaitFor", "Entrypoint", "SecretEnv",
                        "Volumes", "Timing", "PullTiming", "Timeout", "Status", });
        internal_static_google_events_cloud_cloudbuild_v1_Volume_descriptor = getDescriptor().getMessageTypes().get(5);
        internal_static_google_events_cloud_cloudbuild_v1_Volume_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Volume_descriptor,
                new java.lang.String[] { "Name", "Path", });
        internal_static_google_events_cloud_cloudbuild_v1_Results_descriptor = getDescriptor().getMessageTypes().get(6);
        internal_static_google_events_cloud_cloudbuild_v1_Results_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Results_descriptor, new java.lang.String[] { "Images",
                        "BuildStepImages", "ArtifactManifest", "NumArtifacts", "BuildStepOutputs", "ArtifactTiming", });
        internal_static_google_events_cloud_cloudbuild_v1_BuiltImage_descriptor = getDescriptor().getMessageTypes()
                .get(7);
        internal_static_google_events_cloud_cloudbuild_v1_BuiltImage_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuiltImage_descriptor,
                new java.lang.String[] { "Name", "Digest", "PushTiming", });
        internal_static_google_events_cloud_cloudbuild_v1_Artifacts_descriptor = getDescriptor().getMessageTypes()
                .get(8);
        internal_static_google_events_cloud_cloudbuild_v1_Artifacts_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Artifacts_descriptor,
                new java.lang.String[] { "Images", "Objects", });
        internal_static_google_events_cloud_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor = internal_static_google_events_cloud_cloudbuild_v1_Artifacts_descriptor
                .getNestedTypes().get(0);
        internal_static_google_events_cloud_cloudbuild_v1_Artifacts_ArtifactObjects_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Artifacts_ArtifactObjects_descriptor,
                new java.lang.String[] { "Location", "Paths", "Timing", });
        internal_static_google_events_cloud_cloudbuild_v1_TimeSpan_descriptor = getDescriptor().getMessageTypes()
                .get(9);
        internal_static_google_events_cloud_cloudbuild_v1_TimeSpan_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_TimeSpan_descriptor,
                new java.lang.String[] { "StartTime", "EndTime", });
        internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_descriptor = getDescriptor()
                .getMessageTypes().get(10);
        internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_descriptor,
                new java.lang.String[] { "ResolvedStorageSource", "ResolvedRepoSource", "FileHashes", });
        internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor = internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_descriptor
                .getNestedTypes().get(0);
        internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_FileHashesEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_SourceProvenance_FileHashesEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_FileHashes_descriptor = getDescriptor().getMessageTypes()
                .get(11);
        internal_static_google_events_cloud_cloudbuild_v1_FileHashes_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_FileHashes_descriptor,
                new java.lang.String[] { "FileHash", });
        internal_static_google_events_cloud_cloudbuild_v1_Hash_descriptor = getDescriptor().getMessageTypes().get(12);
        internal_static_google_events_cloud_cloudbuild_v1_Hash_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Hash_descriptor,
                new java.lang.String[] { "Type", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_Secret_descriptor = getDescriptor().getMessageTypes().get(13);
        internal_static_google_events_cloud_cloudbuild_v1_Secret_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Secret_descriptor,
                new java.lang.String[] { "KmsKeyName", "SecretEnv", });
        internal_static_google_events_cloud_cloudbuild_v1_Secret_SecretEnvEntry_descriptor = internal_static_google_events_cloud_cloudbuild_v1_Secret_descriptor
                .getNestedTypes().get(0);
        internal_static_google_events_cloud_cloudbuild_v1_Secret_SecretEnvEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_Secret_SecretEnvEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
        internal_static_google_events_cloud_cloudbuild_v1_BuildOptions_descriptor = getDescriptor().getMessageTypes()
                .get(14);
        internal_static_google_events_cloud_cloudbuild_v1_BuildOptions_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_google_events_cloud_cloudbuild_v1_BuildOptions_descriptor,
                new java.lang.String[] { "SourceProvenanceHash", "RequestedVerifyOption", "MachineType", "DiskSizeGb",
                        "SubstitutionOption", "LogStreamingOption", "WorkerPool", "Logging", "Env", "SecretEnv",
                        "Volumes", });
        com.google.protobuf.DurationProto.getDescriptor();
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
