/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/auth/v1/data.proto

package com.google.events.firebase.auth.v1;

public final class Data {
  private Data() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_firebase_auth_v1_AuthEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_firebase_auth_v1_AuthEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_firebase_auth_v1_UserMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_firebase_auth_v1_UserMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_firebase_auth_v1_UserInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_firebase_auth_v1_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n)google/events/firebase/auth/v1/data.pr"
          + "oto\022\036google.events.firebase.auth.v1\032\034goo"
          + "gle/protobuf/struct.proto\032\037google/protob"
          + "uf/timestamp.proto\"\305\002\n\rAuthEventData\022\013\n\003"
          + "uid\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\026\n\016email_verifi"
          + "ed\030\003 \001(\010\022\024\n\014display_name\030\004 \001(\t\022\021\n\tphoto_"
          + "URL\030\005 \001(\t\022\020\n\010disabled\030\006 \001(\010\022>\n\010metadata\030"
          + "\007 \001(\0132,.google.events.firebase.auth.v1.U"
          + "serMetadata\022?\n\rprovider_data\030\010 \003(\0132(.goo"
          + "gle.events.firebase.auth.v1.UserInfo\022\024\n\014"
          + "phone_number\030\t \001(\t\022.\n\rcustom_claims\030\n \001("
          + "\0132\027.google.protobuf.Struct\"v\n\014UserMetada"
          + "ta\022/\n\013create_time\030\001 \001(\0132\032.google.protobu"
          + "f.Timestamp\0225\n\021last_sign_in_time\030\002 \001(\0132\032"
          + ".google.protobuf.Timestamp\"d\n\010UserInfo\022\013"
          + "\n\003uid\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\024\n\014display_na"
          + "me\030\003 \001(\t\022\021\n\tphoto_URL\030\004 \001(\t\022\023\n\013provider_"
          + "id\030\005 \001(\tBP\n\"com.google.events.firebase.a"
          + "uth.v1P\001\252\002\'Google.Events.Protobuf.Fireba"
          + "se.Auth.V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_events_firebase_auth_v1_AuthEventData_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_events_firebase_auth_v1_AuthEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_firebase_auth_v1_AuthEventData_descriptor,
            new java.lang.String[] {
              "Uid",
              "Email",
              "EmailVerified",
              "DisplayName",
              "PhotoURL",
              "Disabled",
              "Metadata",
              "ProviderData",
              "PhoneNumber",
              "CustomClaims",
            });
    internal_static_google_events_firebase_auth_v1_UserMetadata_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_events_firebase_auth_v1_UserMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_firebase_auth_v1_UserMetadata_descriptor,
            new java.lang.String[] {
              "CreateTime", "LastSignInTime",
            });
    internal_static_google_events_firebase_auth_v1_UserInfo_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_events_firebase_auth_v1_UserInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_firebase_auth_v1_UserInfo_descriptor,
            new java.lang.String[] {
              "Uid", "Email", "DisplayName", "PhotoURL", "ProviderId",
            });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
