// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/analytics/v1/data.proto

package com.google.events.firebase.analytics.v1;

public interface AnalyticsLogDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:google.events.firebase.analytics.v1.AnalyticsLogData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * User related dimensions.
     * </pre>
     *
     * <code>.google.events.firebase.analytics.v1.UserDimensions user_dim = 1;</code>
     *
     * @return Whether the userDim field is set.
     */
    boolean hasUserDim();

    /**
     * <pre>
     * User related dimensions.
     * </pre>
     *
     * <code>.google.events.firebase.analytics.v1.UserDimensions user_dim = 1;</code>
     *
     * @return The userDim.
     */
    com.google.events.firebase.analytics.v1.UserDimensions getUserDim();

    /**
     * <pre>
     * User related dimensions.
     * </pre>
     *
     * <code>.google.events.firebase.analytics.v1.UserDimensions user_dim = 1;</code>
     */
    com.google.events.firebase.analytics.v1.UserDimensionsOrBuilder getUserDimOrBuilder();

    /**
     * <pre>
     * A repeated record of event related dimensions.
     * </pre>
     *
     * <code>repeated .google.events.firebase.analytics.v1.EventDimensions event_dim = 2;</code>
     */
    java.util.List<com.google.events.firebase.analytics.v1.EventDimensions> getEventDimList();

    /**
     * <pre>
     * A repeated record of event related dimensions.
     * </pre>
     *
     * <code>repeated .google.events.firebase.analytics.v1.EventDimensions event_dim = 2;</code>
     */
    com.google.events.firebase.analytics.v1.EventDimensions getEventDim(int index);

    /**
     * <pre>
     * A repeated record of event related dimensions.
     * </pre>
     *
     * <code>repeated .google.events.firebase.analytics.v1.EventDimensions event_dim = 2;</code>
     */
    int getEventDimCount();

    /**
     * <pre>
     * A repeated record of event related dimensions.
     * </pre>
     *
     * <code>repeated .google.events.firebase.analytics.v1.EventDimensions event_dim = 2;</code>
     */
    java.util.List<? extends com.google.events.firebase.analytics.v1.EventDimensionsOrBuilder> getEventDimOrBuilderList();

    /**
     * <pre>
     * A repeated record of event related dimensions.
     * </pre>
     *
     * <code>repeated .google.events.firebase.analytics.v1.EventDimensions event_dim = 2;</code>
     */
    com.google.events.firebase.analytics.v1.EventDimensionsOrBuilder getEventDimOrBuilder(int index);
}
