// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/firebase/analytics/v1/data.proto

package com.google.events.firebase.analytics.v1;

/**
 * <pre>
 * Message which contains App Information.
 * </pre>
 *
 * Protobuf type {@code google.events.firebase.analytics.v1.AppInfo}
 */
public final class AppInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.events.firebase.analytics.v1.AppInfo)
    AppInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppInfo.newBuilder() to construct.
  private AppInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppInfo() {
    appVersion_ = "";
    appInstanceId_ = "";
    appStore_ = "";
    appPlatform_ = "";
    appId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.events.firebase.analytics.v1.Data.internal_static_google_events_firebase_analytics_v1_AppInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.events.firebase.analytics.v1.Data.internal_static_google_events_firebase_analytics_v1_AppInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.events.firebase.analytics.v1.AppInfo.class, com.google.events.firebase.analytics.v1.AppInfo.Builder.class);
  }

  public static final int APP_VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object appVersion_;
  /**
   * <pre>
   * The app's version name
   * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
   * </pre>
   *
   * <code>string app_version = 1;</code>
   * @return The appVersion.
   */
  @java.lang.Override
  public java.lang.String getAppVersion() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The app's version name
   * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
   * </pre>
   *
   * <code>string app_version = 1;</code>
   * @return The bytes for appVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppVersionBytes() {
    java.lang.Object ref = appVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_INSTANCE_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object appInstanceId_;
  /**
   * <pre>
   * Unique id for this instance of the app.
   * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
   * </pre>
   *
   * <code>string app_instance_id = 2;</code>
   * @return The appInstanceId.
   */
  @java.lang.Override
  public java.lang.String getAppInstanceId() {
    java.lang.Object ref = appInstanceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appInstanceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique id for this instance of the app.
   * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
   * </pre>
   *
   * <code>string app_instance_id = 2;</code>
   * @return The bytes for appInstanceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppInstanceIdBytes() {
    java.lang.Object ref = appInstanceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appInstanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_STORE_FIELD_NUMBER = 3;
  private volatile java.lang.Object appStore_;
  /**
   * <pre>
   * The identifier of the store that installed the app.
   * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
   * "com.nokia.nstore"
   * </pre>
   *
   * <code>string app_store = 3;</code>
   * @return The appStore.
   */
  @java.lang.Override
  public java.lang.String getAppStore() {
    java.lang.Object ref = appStore_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appStore_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The identifier of the store that installed the app.
   * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
   * "com.nokia.nstore"
   * </pre>
   *
   * <code>string app_store = 3;</code>
   * @return The bytes for appStore.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppStoreBytes() {
    java.lang.Object ref = appStore_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appStore_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_PLATFORM_FIELD_NUMBER = 4;
  private volatile java.lang.Object appPlatform_;
  /**
   * <pre>
   * The app platform.
   * Eg "ANDROID", "IOS".
   * </pre>
   *
   * <code>string app_platform = 4;</code>
   * @return The appPlatform.
   */
  @java.lang.Override
  public java.lang.String getAppPlatform() {
    java.lang.Object ref = appPlatform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appPlatform_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The app platform.
   * Eg "ANDROID", "IOS".
   * </pre>
   *
   * <code>string app_platform = 4;</code>
   * @return The bytes for appPlatform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppPlatformBytes() {
    java.lang.Object ref = appPlatform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appPlatform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APP_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object appId_;
  /**
   * <pre>
   * Unique application identifier within an app store.
   * </pre>
   *
   * <code>string app_id = 5;</code>
   * @return The appId.
   */
  @java.lang.Override
  public java.lang.String getAppId() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique application identifier within an app store.
   * </pre>
   *
   * <code>string app_id = 5;</code>
   * @return The bytes for appId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    java.lang.Object ref = appId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appInstanceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appInstanceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appStore_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appStore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appPlatform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appPlatform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appVersion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appInstanceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appInstanceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appStore_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appStore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appPlatform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appPlatform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.events.firebase.analytics.v1.AppInfo)) {
      return super.equals(obj);
    }
    com.google.events.firebase.analytics.v1.AppInfo other = (com.google.events.firebase.analytics.v1.AppInfo) obj;

    if (!getAppVersion()
        .equals(other.getAppVersion())) return false;
    if (!getAppInstanceId()
        .equals(other.getAppInstanceId())) return false;
    if (!getAppStore()
        .equals(other.getAppStore())) return false;
    if (!getAppPlatform()
        .equals(other.getAppPlatform())) return false;
    if (!getAppId()
        .equals(other.getAppId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getAppVersion().hashCode();
    hash = (37 * hash) + APP_INSTANCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppInstanceId().hashCode();
    hash = (37 * hash) + APP_STORE_FIELD_NUMBER;
    hash = (53 * hash) + getAppStore().hashCode();
    hash = (37 * hash) + APP_PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getAppPlatform().hashCode();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.events.firebase.analytics.v1.AppInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.events.firebase.analytics.v1.AppInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message which contains App Information.
   * </pre>
   *
   * Protobuf type {@code google.events.firebase.analytics.v1.AppInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.events.firebase.analytics.v1.AppInfo)
      com.google.events.firebase.analytics.v1.AppInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.events.firebase.analytics.v1.Data.internal_static_google_events_firebase_analytics_v1_AppInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.events.firebase.analytics.v1.Data.internal_static_google_events_firebase_analytics_v1_AppInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.events.firebase.analytics.v1.AppInfo.class, com.google.events.firebase.analytics.v1.AppInfo.Builder.class);
    }

    // Construct using com.google.events.firebase.analytics.v1.AppInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      appVersion_ = "";

      appInstanceId_ = "";

      appStore_ = "";

      appPlatform_ = "";

      appId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.events.firebase.analytics.v1.Data.internal_static_google_events_firebase_analytics_v1_AppInfo_descriptor;
    }

    @java.lang.Override
    public com.google.events.firebase.analytics.v1.AppInfo getDefaultInstanceForType() {
      return com.google.events.firebase.analytics.v1.AppInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.events.firebase.analytics.v1.AppInfo build() {
      com.google.events.firebase.analytics.v1.AppInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.events.firebase.analytics.v1.AppInfo buildPartial() {
      com.google.events.firebase.analytics.v1.AppInfo result = new com.google.events.firebase.analytics.v1.AppInfo(this);
      result.appVersion_ = appVersion_;
      result.appInstanceId_ = appInstanceId_;
      result.appStore_ = appStore_;
      result.appPlatform_ = appPlatform_;
      result.appId_ = appId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.events.firebase.analytics.v1.AppInfo) {
        return mergeFrom((com.google.events.firebase.analytics.v1.AppInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.events.firebase.analytics.v1.AppInfo other) {
      if (other == com.google.events.firebase.analytics.v1.AppInfo.getDefaultInstance()) return this;
      if (!other.getAppVersion().isEmpty()) {
        appVersion_ = other.appVersion_;
        onChanged();
      }
      if (!other.getAppInstanceId().isEmpty()) {
        appInstanceId_ = other.appInstanceId_;
        onChanged();
      }
      if (!other.getAppStore().isEmpty()) {
        appStore_ = other.appStore_;
        onChanged();
      }
      if (!other.getAppPlatform().isEmpty()) {
        appPlatform_ = other.appPlatform_;
        onChanged();
      }
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              appVersion_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              appInstanceId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              appStore_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              appPlatform_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              appId_ = input.readStringRequireUtf8();

              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object appVersion_ = "";
    /**
     * <pre>
     * The app's version name
     * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
     * </pre>
     *
     * <code>string app_version = 1;</code>
     * @return The appVersion.
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The app's version name
     * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
     * </pre>
     *
     * <code>string app_version = 1;</code>
     * @return The bytes for appVersion.
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The app's version name
     * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
     * </pre>
     *
     * <code>string app_version = 1;</code>
     * @param value The appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app's version name
     * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
     * </pre>
     *
     * <code>string app_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppVersion() {
      
      appVersion_ = getDefaultInstance().getAppVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app's version name
     * Examples: "1.0", "4.3.1.1.213361", "2.3 (1824253)", "v1.8b22p6"
     * </pre>
     *
     * <code>string app_version = 1;</code>
     * @param value The bytes for appVersion to set.
     * @return This builder for chaining.
     */
    public Builder setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appInstanceId_ = "";
    /**
     * <pre>
     * Unique id for this instance of the app.
     * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
     * </pre>
     *
     * <code>string app_instance_id = 2;</code>
     * @return The appInstanceId.
     */
    public java.lang.String getAppInstanceId() {
      java.lang.Object ref = appInstanceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appInstanceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique id for this instance of the app.
     * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
     * </pre>
     *
     * <code>string app_instance_id = 2;</code>
     * @return The bytes for appInstanceId.
     */
    public com.google.protobuf.ByteString
        getAppInstanceIdBytes() {
      java.lang.Object ref = appInstanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique id for this instance of the app.
     * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
     * </pre>
     *
     * <code>string app_instance_id = 2;</code>
     * @param value The appInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setAppInstanceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique id for this instance of the app.
     * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
     * </pre>
     *
     * <code>string app_instance_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppInstanceId() {
      
      appInstanceId_ = getDefaultInstance().getAppInstanceId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique id for this instance of the app.
     * Example: "71683BF9FA3B4B0D9535A1F05188BAF3"
     * </pre>
     *
     * <code>string app_instance_id = 2;</code>
     * @param value The bytes for appInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setAppInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appInstanceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appStore_ = "";
    /**
     * <pre>
     * The identifier of the store that installed the app.
     * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
     * "com.nokia.nstore"
     * </pre>
     *
     * <code>string app_store = 3;</code>
     * @return The appStore.
     */
    public java.lang.String getAppStore() {
      java.lang.Object ref = appStore_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appStore_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The identifier of the store that installed the app.
     * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
     * "com.nokia.nstore"
     * </pre>
     *
     * <code>string app_store = 3;</code>
     * @return The bytes for appStore.
     */
    public com.google.protobuf.ByteString
        getAppStoreBytes() {
      java.lang.Object ref = appStore_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appStore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The identifier of the store that installed the app.
     * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
     * "com.nokia.nstore"
     * </pre>
     *
     * <code>string app_store = 3;</code>
     * @param value The appStore to set.
     * @return This builder for chaining.
     */
    public Builder setAppStore(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appStore_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifier of the store that installed the app.
     * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
     * "com.nokia.nstore"
     * </pre>
     *
     * <code>string app_store = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppStore() {
      
      appStore_ = getDefaultInstance().getAppStore();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The identifier of the store that installed the app.
     * Eg. "com.sec.android.app.samsungapps", "com.amazon.venezia",
     * "com.nokia.nstore"
     * </pre>
     *
     * <code>string app_store = 3;</code>
     * @param value The bytes for appStore to set.
     * @return This builder for chaining.
     */
    public Builder setAppStoreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appStore_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appPlatform_ = "";
    /**
     * <pre>
     * The app platform.
     * Eg "ANDROID", "IOS".
     * </pre>
     *
     * <code>string app_platform = 4;</code>
     * @return The appPlatform.
     */
    public java.lang.String getAppPlatform() {
      java.lang.Object ref = appPlatform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appPlatform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The app platform.
     * Eg "ANDROID", "IOS".
     * </pre>
     *
     * <code>string app_platform = 4;</code>
     * @return The bytes for appPlatform.
     */
    public com.google.protobuf.ByteString
        getAppPlatformBytes() {
      java.lang.Object ref = appPlatform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appPlatform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The app platform.
     * Eg "ANDROID", "IOS".
     * </pre>
     *
     * <code>string app_platform = 4;</code>
     * @param value The appPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setAppPlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appPlatform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app platform.
     * Eg "ANDROID", "IOS".
     * </pre>
     *
     * <code>string app_platform = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppPlatform() {
      
      appPlatform_ = getDefaultInstance().getAppPlatform();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The app platform.
     * Eg "ANDROID", "IOS".
     * </pre>
     *
     * <code>string app_platform = 4;</code>
     * @param value The bytes for appPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setAppPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appPlatform_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object appId_ = "";
    /**
     * <pre>
     * Unique application identifier within an app store.
     * </pre>
     *
     * <code>string app_id = 5;</code>
     * @return The appId.
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique application identifier within an app store.
     * </pre>
     *
     * <code>string app_id = 5;</code>
     * @return The bytes for appId.
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique application identifier within an app store.
     * </pre>
     *
     * <code>string app_id = 5;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique application identifier within an app store.
     * </pre>
     *
     * <code>string app_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      
      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique application identifier within an app store.
     * </pre>
     *
     * <code>string app_id = 5;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.events.firebase.analytics.v1.AppInfo)
  }

  // @@protoc_insertion_point(class_scope:google.events.firebase.analytics.v1.AppInfo)
  private static final com.google.events.firebase.analytics.v1.AppInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.events.firebase.analytics.v1.AppInfo();
  }

  public static com.google.events.firebase.analytics.v1.AppInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppInfo>
      PARSER = new com.google.protobuf.AbstractParser<AppInfo>() {
    @java.lang.Override
    public AppInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AppInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.events.firebase.analytics.v1.AppInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

