/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/datastream/v1/data.proto

package com.google.events.cloud.datastream.v1;

public interface PostgresqlProfileOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.events.cloud.datastream.v1.PostgresqlProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. Hostname for the PostgreSQL connection.
   * </pre>
   *
   * <code>string hostname = 1;</code>
   *
   * @return The hostname.
   */
  java.lang.String getHostname();

  /**
   *
   *
   * <pre>
   * Required. Hostname for the PostgreSQL connection.
   * </pre>
   *
   * <code>string hostname = 1;</code>
   *
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString getHostnameBytes();

  /**
   *
   *
   * <pre>
   * Port for the PostgreSQL connection, default value is 5432.
   * </pre>
   *
   * <code>int32 port = 2;</code>
   *
   * @return The port.
   */
  int getPort();

  /**
   *
   *
   * <pre>
   * Required. Username for the PostgreSQL connection.
   * </pre>
   *
   * <code>string username = 3;</code>
   *
   * @return The username.
   */
  java.lang.String getUsername();

  /**
   *
   *
   * <pre>
   * Required. Username for the PostgreSQL connection.
   * </pre>
   *
   * <code>string username = 3;</code>
   *
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString getUsernameBytes();

  /**
   *
   *
   * <pre>
   * Required. Database for the PostgreSQL connection.
   * </pre>
   *
   * <code>string database = 5;</code>
   *
   * @return The database.
   */
  java.lang.String getDatabase();

  /**
   *
   *
   * <pre>
   * Required. Database for the PostgreSQL connection.
   * </pre>
   *
   * <code>string database = 5;</code>
   *
   * @return The bytes for database.
   */
  com.google.protobuf.ByteString getDatabaseBytes();
}
