/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/apigeeregistry/v1/data.proto

package com.google.events.cloud.apigeeregistry.v1;

public final class Data {
  private Data() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_Instance_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_Instance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_Instance_Config_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_Instance_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_Api_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_Api_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_Api_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_Api_AnnotationsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_Api_AnnotationsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_AnnotationsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_AnnotationsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_AnnotationsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_AnnotationsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_AnnotationsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_AnnotationsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersionEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiVersionEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_InstanceEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_InstanceEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpecEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiSpecEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeploymentEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiDeploymentEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apigeeregistry_v1_ApiEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apigeeregistry_v1_ApiEventData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n0google/events/cloud/apigeeregistry/v1/"
          + "data.proto\022%google.events.cloud.apigeere"
          + "gistry.v1\032\037google/protobuf/timestamp.pro"
          + "to\"\302\003\n\010Instance\022\014\n\004name\030\001 \001(\t\022/\n\013create_"
          + "time\030\002 \001(\0132\032.google.protobuf.Timestamp\022/"
          + "\n\013update_time\030\003 \001(\0132\032.google.protobuf.Ti"
          + "mestamp\022D\n\005state\030\004 \001(\01625.google.events.c"
          + "loud.apigeeregistry.v1.Instance.State\022\025\n"
          + "\rstate_message\030\005 \001(\t\022F\n\006config\030\006 \001(\01326.g"
          + "oogle.events.cloud.apigeeregistry.v1.Ins"
          + "tance.Config\0321\n\006Config\022\020\n\010location\030\001 \001(\t"
          + "\022\025\n\rcmek_key_name\030\002 \001(\t\"n\n\005State\022\025\n\021STAT"
          + "E_UNSPECIFIED\020\000\022\014\n\010INACTIVE\020\001\022\014\n\010CREATIN"
          + "G\020\002\022\n\n\006ACTIVE\020\003\022\014\n\010UPDATING\020\004\022\014\n\010DELETIN"
          + "G\020\005\022\n\n\006FAILED\020\006\"\360\003\n\003Api\022\014\n\004name\030\001 \001(\t\022\024\n"
          + "\014display_name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t"
          + "\022/\n\013create_time\030\004 \001(\0132\032.google.protobuf."
          + "Timestamp\022/\n\013update_time\030\005 \001(\0132\032.google."
          + "protobuf.Timestamp\022\024\n\014availability\030\006 \001(\t"
          + "\022\033\n\023recommended_version\030\007 \001(\t\022\036\n\026recomme"
          + "nded_deployment\030\010 \001(\t\022F\n\006labels\030\t \003(\01326."
          + "google.events.cloud.apigeeregistry.v1.Ap"
          + "i.LabelsEntry\022P\n\013annotations\030\n \003(\0132;.goo"
          + "gle.events.cloud.apigeeregistry.v1.Api.A"
          + "nnotationsEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 "
          + "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0322\n\020AnnotationsEnt"
          + "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\301\003\n\nA"
          + "piVersion\022\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030"
          + "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022/\n\013create_tim"
          + "e\030\004 \001(\0132\032.google.protobuf.Timestamp\022/\n\013u"
          + "pdate_time\030\005 \001(\0132\032.google.protobuf.Times"
          + "tamp\022\r\n\005state\030\006 \001(\t\022M\n\006labels\030\007 \003(\0132=.go"
          + "ogle.events.cloud.apigeeregistry.v1.ApiV"
          + "ersion.LabelsEntry\022W\n\013annotations\030\010 \003(\0132"
          + "B.google.events.cloud.apigeeregistry.v1."
          + "ApiVersion.AnnotationsEntry\032-\n\013LabelsEnt"
          + "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0322\n\020An"
          + "notationsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001"
          + "(\t:\0028\001\"\306\004\n\007ApiSpec\022\014\n\004name\030\001 \001(\t\022\020\n\010file"
          + "name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\023\n\013revis"
          + "ion_id\030\004 \001(\t\022/\n\013create_time\030\005 \001(\0132\032.goog"
          + "le.protobuf.Timestamp\0228\n\024revision_create"
          + "_time\030\006 \001(\0132\032.google.protobuf.Timestamp\022"
          + "8\n\024revision_update_time\030\007 \001(\0132\032.google.p"
          + "rotobuf.Timestamp\022\021\n\tmime_type\030\010 \001(\t\022\022\n\n"
          + "size_bytes\030\t \001(\005\022\014\n\004hash\030\n \001(\t\022\022\n\nsource"
          + "_uri\030\013 \001(\t\022J\n\006labels\030\016 \003(\0132:.google.even"
          + "ts.cloud.apigeeregistry.v1.ApiSpec.Label"
          + "sEntry\022T\n\013annotations\030\017 \003(\0132?.google.eve"
          + "nts.cloud.apigeeregistry.v1.ApiSpec.Anno"
          + "tationsEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t"
          + "\022\r\n\005value\030\002 \001(\t:\0028\001\0322\n\020AnnotationsEntry\022"
          + "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\226\005\n\rApiD"
          + "eployment\022\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030"
          + "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\023\n\013revision_i"
          + "d\030\004 \001(\t\022/\n\013create_time\030\005 \001(\0132\032.google.pr"
          + "otobuf.Timestamp\0228\n\024revision_create_time"
          + "\030\006 \001(\0132\032.google.protobuf.Timestamp\0228\n\024re"
          + "vision_update_time\030\007 \001(\0132\032.google.protob"
          + "uf.Timestamp\022\031\n\021api_spec_revision\030\010 \001(\t\022"
          + "\024\n\014endpoint_uri\030\t \001(\t\022\034\n\024external_channe"
          + "l_uri\030\n \001(\t\022\031\n\021intended_audience\030\013 \001(\t\022\027"
          + "\n\017access_guidance\030\014 \001(\t\022P\n\006labels\030\016 \003(\0132"
          + "@.google.events.cloud.apigeeregistry.v1."
          + "ApiDeployment.LabelsEntry\022Z\n\013annotations"
          + "\030\017 \003(\0132E.google.events.cloud.apigeeregis"
          + "try.v1.ApiDeployment.AnnotationsEntry\032-\n"
          + "\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
          + ":\0028\001\0322\n\020AnnotationsEntry\022\013\n\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"j\n\023ApiVersionEventData\022"
          + "G\n\007payload\030\001 \001(\01321.google.events.cloud.a"
          + "pigeeregistry.v1.ApiVersionH\000\210\001\001B\n\n\010_pay"
          + "load\"f\n\021InstanceEventData\022E\n\007payload\030\001 \001"
          + "(\0132/.google.events.cloud.apigeeregistry."
          + "v1.InstanceH\000\210\001\001B\n\n\010_payload\"d\n\020ApiSpecE"
          + "ventData\022D\n\007payload\030\001 \001(\0132..google.event"
          + "s.cloud.apigeeregistry.v1.ApiSpecH\000\210\001\001B\n"
          + "\n\010_payload\"p\n\026ApiDeploymentEventData\022J\n\007"
          + "payload\030\001 \001(\01324.google.events.cloud.apig"
          + "eeregistry.v1.ApiDeploymentH\000\210\001\001B\n\n\010_pay"
          + "load\"\\\n\014ApiEventData\022@\n\007payload\030\001 \001(\0132*."
          + "google.events.cloud.apigeeregistry.v1.Ap"
          + "iH\000\210\001\001B\n\n\010_payloadB\262\001\n)com.google.events"
          + ".cloud.apigeeregistry.v1P\001\252\002.Google.Even"
          + "ts.Protobuf.Cloud.ApigeeRegistry.V1\312\002%Go"
          + "ogle\\Events\\Cloud\\ApigeeRegistry\\V1\352\002)Go"
          + "ogle::Events::Cloud::ApigeeRegistry::V1b"
          + "\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_events_cloud_apigeeregistry_v1_Instance_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_Instance_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_Instance_descriptor,
            new java.lang.String[] {
              "Name", "CreateTime", "UpdateTime", "State", "StateMessage", "Config",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_Instance_Config_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_Instance_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_Instance_Config_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_Instance_Config_descriptor,
            new java.lang.String[] {
              "Location", "CmekKeyName",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_Api_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_events_cloud_apigeeregistry_v1_Api_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_Api_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "CreateTime",
              "UpdateTime",
              "Availability",
              "RecommendedVersion",
              "RecommendedDeployment",
              "Labels",
              "Annotations",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_Api_LabelsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_Api_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_Api_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_Api_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_Api_AnnotationsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_Api_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apigeeregistry_v1_Api_AnnotationsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_Api_AnnotationsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "CreateTime",
              "UpdateTime",
              "State",
              "Labels",
              "Annotations",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_LabelsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_AnnotationsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_AnnotationsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiVersion_AnnotationsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_descriptor,
            new java.lang.String[] {
              "Name",
              "Filename",
              "Description",
              "RevisionId",
              "CreateTime",
              "RevisionCreateTime",
              "RevisionUpdateTime",
              "MimeType",
              "SizeBytes",
              "Hash",
              "SourceUri",
              "Labels",
              "Annotations",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_LabelsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_AnnotationsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_AnnotationsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiSpec_AnnotationsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "RevisionId",
              "CreateTime",
              "RevisionCreateTime",
              "RevisionUpdateTime",
              "ApiSpecRevision",
              "EndpointUri",
              "ExternalChannelUri",
              "IntendedAudience",
              "AccessGuidance",
              "Labels",
              "Annotations",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_LabelsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_AnnotationsEntry_descriptor =
        internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_AnnotationsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiDeployment_AnnotationsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersionEventData_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiVersionEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiVersionEventData_descriptor,
            new java.lang.String[] {
              "Payload", "Payload",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_InstanceEventData_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_events_cloud_apigeeregistry_v1_InstanceEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_InstanceEventData_descriptor,
            new java.lang.String[] {
              "Payload", "Payload",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpecEventData_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiSpecEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiSpecEventData_descriptor,
            new java.lang.String[] {
              "Payload", "Payload",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeploymentEventData_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiDeploymentEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiDeploymentEventData_descriptor,
            new java.lang.String[] {
              "Payload", "Payload",
            });
    internal_static_google_events_cloud_apigeeregistry_v1_ApiEventData_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_events_cloud_apigeeregistry_v1_ApiEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apigeeregistry_v1_ApiEventData_descriptor,
            new java.lang.String[] {
              "Payload", "Payload",
            });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
