/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/events/cloud/apihub/v1/data.proto

package com.google.events.cloud.apihub.v1;

public final class Data {
  private Data() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Api_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Api_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Api_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Api_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Version_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Version_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Version_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Spec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Spec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Spec_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Spec_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Deployment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Deployment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Deployment_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Deployment_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Attribute_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Attribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Attribute_AllowedValue_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Attribute_AllowedValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_SpecContents_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_SpecContents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_SpecDetails_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_SpecDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_OpenApiSpecDetails_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_OpenApiSpecDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Owner_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Owner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Documentation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Documentation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_AttributeValues_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_AttributeValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_AttributeValues_EnumAttributeValues_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_AttributeValues_EnumAttributeValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_AttributeValues_StringAttributeValues_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_AttributeValues_StringAttributeValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Dependency_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Dependency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Dependency_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Dependency_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_DependencyEntityReference_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_DependencyEntityReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_DependencyErrorDetail_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_DependencyErrorDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_LintResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_LintResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_LintResponse_SummaryEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_LintResponse_SummaryEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Issue_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Issue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Range_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Range_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_Point_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_Config_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ApiHubInstance_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ExternalApi_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ExternalApi_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ExternalApi_AttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ExternalApi_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_HostProjectRegistration_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_HostProjectRegistration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ApiEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ApiEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_VersionEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_VersionEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_SpecEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_SpecEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_DeploymentEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_DeploymentEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_AttributeEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_AttributeEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ExternalApiEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ExternalApiEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_DependencyEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_DependencyEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_HostProjectRegistrationEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_HostProjectRegistrationEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_ApiHubInstanceEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_ApiHubInstanceEventData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachmentEventData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachmentEventData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n(google/events/cloud/apihub/v1/data.pro"
          + "to\022\035google.events.cloud.apihub.v1\032\037googl"
          + "e/protobuf/timestamp.proto\"\306\006\n\003Api\022\014\n\004na"
          + "me\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022\023\n\013descri"
          + "ption\030\003 \001(\t\022C\n\rdocumentation\030\004 \001(\0132,.goo"
          + "gle.events.cloud.apihub.v1.Documentation"
          + "\0223\n\005owner\030\005 \001(\0132$.google.events.cloud.ap"
          + "ihub.v1.Owner\022\020\n\010versions\030\006 \003(\t\022/\n\013creat"
          + "e_time\030\007 \001(\0132\032.google.protobuf.Timestamp"
          + "\022/\n\013update_time\030\010 \001(\0132\032.google.protobuf."
          + "Timestamp\022C\n\013target_user\030\t \001(\0132..google."
          + "events.cloud.apihub.v1.AttributeValues\022<"
          + "\n\004team\030\n \001(\0132..google.events.cloud.apihu"
          + "b.v1.AttributeValues\022E\n\rbusiness_unit\030\013 "
          + "\001(\0132..google.events.cloud.apihub.v1.Attr"
          + "ibuteValues\022F\n\016maturity_level\030\014 \001(\0132..go"
          + "ogle.events.cloud.apihub.v1.AttributeVal"
          + "ues\022F\n\nattributes\030\r \003(\01322.google.events."
          + "cloud.apihub.v1.Api.AttributesEntry\022A\n\ta"
          + "pi_style\030\016 \001(\0132..google.events.cloud.api"
          + "hub.v1.AttributeValues\022\030\n\020selected_versi"
          + "on\030\017 \001(\t\032a\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t"
          + "\022=\n\005value\030\002 \001(\0132..google.events.cloud.ap"
          + "ihub.v1.AttributeValues:\0028\001\"\324\005\n\007Version\022"
          + "\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022\023\n\013d"
          + "escription\030\003 \001(\t\022C\n\rdocumentation\030\004 \001(\0132"
          + ",.google.events.cloud.apihub.v1.Document"
          + "ation\022\r\n\005specs\030\005 \003(\t\022\026\n\016api_operations\030\006"
          + " \003(\t\022\023\n\013definitions\030\007 \003(\t\022\023\n\013deployments"
          + "\030\010 \003(\t\022/\n\013create_time\030\t \001(\0132\032.google.pro"
          + "tobuf.Timestamp\022/\n\013update_time\030\n \001(\0132\032.g"
          + "oogle.protobuf.Timestamp\022A\n\tlifecycle\030\013 "
          + "\001(\0132..google.events.cloud.apihub.v1.Attr"
          + "ibuteValues\022B\n\ncompliance\030\014 \001(\0132..google"
          + ".events.cloud.apihub.v1.AttributeValues\022"
          + "E\n\raccreditation\030\r \001(\0132..google.events.c"
          + "loud.apihub.v1.AttributeValues\022J\n\nattrib"
          + "utes\030\016 \003(\01326.google.events.cloud.apihub."
          + "v1.Version.AttributesEntry\022\033\n\023selected_d"
          + "eployment\030\020 \001(\t\032a\n\017AttributesEntry\022\013\n\003ke"
          + "y\030\001 \001(\t\022=\n\005value\030\002 \001(\0132..google.events.c"
          + "loud.apihub.v1.AttributeValues:\0028\001\"\325\004\n\004S"
          + "pec\022\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022"
          + "A\n\tspec_type\030\003 \001(\0132..google.events.cloud"
          + ".apihub.v1.AttributeValues\022;\n\007details\030\005 "
          + "\001(\0132*.google.events.cloud.apihub.v1.Spec"
          + "Details\022\022\n\nsource_uri\030\006 \001(\t\022/\n\013create_ti"
          + "me\030\007 \001(\0132\032.google.protobuf.Timestamp\022/\n\013"
          + "update_time\030\010 \001(\0132\032.google.protobuf.Time"
          + "stamp\022B\n\rlint_response\030\t \001(\0132+.google.ev"
          + "ents.cloud.apihub.v1.LintResponse\022G\n\natt"
          + "ributes\030\n \003(\01323.google.events.cloud.apih"
          + "ub.v1.Spec.AttributesEntry\022C\n\rdocumentat"
          + "ion\030\013 \001(\0132,.google.events.cloud.apihub.v"
          + "1.Documentation\032a\n\017AttributesEntry\022\013\n\003ke"
          + "y\030\001 \001(\t\022=\n\005value\030\002 \001(\0132..google.events.c"
          + "loud.apihub.v1.AttributeValues:\0028\001\"\250\005\n\nD"
          + "eployment\022\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030"
          + "\002 \001(\t\022\023\n\013description\030\003 \001(\t\022C\n\rdocumentat"
          + "ion\030\004 \001(\0132,.google.events.cloud.apihub.v"
          + "1.Documentation\022G\n\017deployment_type\030\005 \001(\013"
          + "2..google.events.cloud.apihub.v1.Attribu"
          + "teValues\022\024\n\014resource_uri\030\006 \001(\t\022\021\n\tendpoi"
          + "nts\030\007 \003(\t\022\024\n\014api_versions\030\010 \003(\t\022/\n\013creat"
          + "e_time\030\t \001(\0132\032.google.protobuf.Timestamp"
          + "\022/\n\013update_time\030\n \001(\0132\032.google.protobuf."
          + "Timestamp\022;\n\003slo\030\013 \001(\0132..google.events.c"
          + "loud.apihub.v1.AttributeValues\022C\n\013enviro"
          + "nment\030\014 \001(\0132..google.events.cloud.apihub"
          + ".v1.AttributeValues\022M\n\nattributes\030\r \003(\0132"
          + "9.google.events.cloud.apihub.v1.Deployme"
          + "nt.AttributesEntry\032a\n\017AttributesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022=\n\005value\030\002 \001(\0132..google.event"
          + "s.cloud.apihub.v1.AttributeValues:\0028\001\"\220\007"
          + "\n\tAttribute\022\014\n\004name\030\001 \001(\t\022\024\n\014display_nam"
          + "e\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022P\n\017definiti"
          + "on_type\030\004 \001(\01627.google.events.cloud.apih"
          + "ub.v1.Attribute.DefinitionType\022=\n\005scope\030"
          + "\005 \001(\0162..google.events.cloud.apihub.v1.At"
          + "tribute.Scope\022D\n\tdata_type\030\006 \001(\01621.googl"
          + "e.events.cloud.apihub.v1.Attribute.DataT"
          + "ype\022M\n\016allowed_values\030\007 \003(\01325.google.eve"
          + "nts.cloud.apihub.v1.Attribute.AllowedVal"
          + "ue\022\023\n\013cardinality\030\010 \001(\005\022\021\n\tmandatory\030\t \001"
          + "(\010\022/\n\013create_time\030\n \001(\0132\032.google.protobu"
          + "f.Timestamp\022/\n\013update_time\030\013 \001(\0132\032.googl"
          + "e.protobuf.Timestamp\032X\n\014AllowedValue\022\n\n\002"
          + "id\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022\023\n\013descri"
          + "ption\030\003 \001(\t\022\021\n\timmutable\030\004 \001(\010\"W\n\016Defini"
          + "tionType\022\037\n\033DEFINITION_TYPE_UNSPECIFIED\020"
          + "\000\022\022\n\016SYSTEM_DEFINED\020\001\022\020\n\014USER_DEFINED\020\002\""
          + "\237\001\n\005Scope\022\025\n\021SCOPE_UNSPECIFIED\020\000\022\007\n\003API\020"
          + "\001\022\013\n\007VERSION\020\002\022\010\n\004SPEC\020\003\022\021\n\rAPI_OPERATIO"
          + "N\020\004\022\016\n\nDEPLOYMENT\020\005\022\016\n\nDEPENDENCY\020\006\022\016\n\nD"
          + "EFINITION\020\007\022\020\n\014EXTERNAL_API\020\010\022\n\n\006PLUGIN\020"
          + "\t\"E\n\010DataType\022\031\n\025DATA_TYPE_UNSPECIFIED\020\000"
          + "\022\010\n\004ENUM\020\001\022\010\n\004JSON\020\002\022\n\n\006STRING\020\003\"3\n\014Spec"
          + "Contents\022\020\n\010contents\030\001 \001(\014\022\021\n\tmime_type\030"
          + "\002 \001(\t\"\201\001\n\013SpecDetails\022R\n\025open_api_spec_d"
          + "etails\030\002 \001(\01321.google.events.cloud.apihu"
          + "b.v1.OpenApiSpecDetailsH\000\022\023\n\013description"
          + "\030\001 \001(\tB\t\n\007details\"\213\002\n\022OpenApiSpecDetails"
          + "\022H\n\006format\030\001 \001(\01628.google.events.cloud.a"
          + "pihub.v1.OpenApiSpecDetails.Format\022\017\n\007ve"
          + "rsion\030\002 \001(\t\0223\n\005owner\030\003 \001(\0132$.google.even"
          + "ts.cloud.apihub.v1.Owner\"e\n\006Format\022\026\n\022FO"
          + "RMAT_UNSPECIFIED\020\000\022\025\n\021OPEN_API_SPEC_2_0\020"
          + "\001\022\025\n\021OPEN_API_SPEC_3_0\020\002\022\025\n\021OPEN_API_SPE"
          + "C_3_1\020\003\",\n\005Owner\022\024\n\014display_name\030\001 \001(\t\022\r"
          + "\n\005email\030\002 \001(\t\"%\n\rDocumentation\022\024\n\014extern"
          + "al_uri\030\001 \001(\t\"\313\003\n\017AttributeValues\022Y\n\013enum"
          + "_values\030\002 \001(\0132B.google.events.cloud.apih"
          + "ub.v1.AttributeValues.EnumAttributeValue"
          + "sH\000\022]\n\rstring_values\030\003 \001(\0132D.google.even"
          + "ts.cloud.apihub.v1.AttributeValues.Strin"
          + "gAttributeValuesH\000\022[\n\013json_values\030\004 \001(\0132"
          + "D.google.events.cloud.apihub.v1.Attribut"
          + "eValues.StringAttributeValuesH\000\022\021\n\tattri"
          + "bute\030\001 \001(\t\032\\\n\023EnumAttributeValues\022E\n\006val"
          + "ues\030\001 \003(\01325.google.events.cloud.apihub.v"
          + "1.Attribute.AllowedValue\032\'\n\025StringAttrib"
          + "uteValues\022\016\n\006values\030\001 \003(\tB\007\n\005Value\"\262\006\n\nD"
          + "ependency\022\014\n\004name\030\001 \001(\t\022J\n\010consumer\030\002 \001("
          + "\01328.google.events.cloud.apihub.v1.Depend"
          + "encyEntityReference\022J\n\010supplier\030\003 \001(\01328."
          + "google.events.cloud.apihub.v1.Dependency"
          + "EntityReference\022>\n\005state\030\004 \001(\0162/.google."
          + "events.cloud.apihub.v1.Dependency.State\022"
          + "\023\n\013description\030\005 \001(\t\022O\n\016discovery_mode\030\006"
          + " \001(\01627.google.events.cloud.apihub.v1.Dep"
          + "endency.DiscoveryMode\022J\n\014error_detail\030\007 "
          + "\001(\01324.google.events.cloud.apihub.v1.Depe"
          + "ndencyErrorDetail\022/\n\013create_time\030\010 \001(\0132\032"
          + ".google.protobuf.Timestamp\022/\n\013update_tim"
          + "e\030\t \001(\0132\032.google.protobuf.Timestamp\022M\n\na"
          + "ttributes\030\n \003(\01329.google.events.cloud.ap"
          + "ihub.v1.Dependency.AttributesEntry\032a\n\017At"
          + "tributesEntry\022\013\n\003key\030\001 \001(\t\022=\n\005value\030\002 \001("
          + "\0132..google.events.cloud.apihub.v1.Attrib"
          + "uteValues:\0028\001\";\n\005State\022\025\n\021STATE_UNSPECIF"
          + "IED\020\000\022\014\n\010PROPOSED\020\001\022\r\n\tVALIDATED\020\002\";\n\rDi"
          + "scoveryMode\022\036\n\032DISCOVERY_MODE_UNSPECIFIE"
          + "D\020\000\022\n\n\006MANUAL\020\001\"\210\001\n\031DependencyEntityRefe"
          + "rence\022!\n\027operation_resource_name\030\002 \001(\tH\000"
          + "\022$\n\032external_api_resource_name\030\003 \001(\tH\000\022\024"
          + "\n\014display_name\030\001 \001(\tB\014\n\nidentifier\"\342\001\n\025D"
          + "ependencyErrorDetail\022I\n\005error\030\001 \001(\0162:.go"
          + "ogle.events.cloud.apihub.v1.DependencyEr"
          + "rorDetail.Error\022.\n\nerror_time\030\002 \001(\0132\032.go"
          + "ogle.protobuf.Timestamp\"N\n\005Error\022\025\n\021ERRO"
          + "R_UNSPECIFIED\020\000\022\026\n\022SUPPLIER_NOT_FOUND\020\001\022"
          + "\026\n\022SUPPLIER_RECREATED\020\002\"\232\003\n\014LintResponse"
          + "\0224\n\006issues\030\001 \003(\0132$.google.events.cloud.a"
          + "pihub.v1.Issue\022I\n\007summary\030\002 \003(\01328.google"
          + ".events.cloud.apihub.v1.LintResponse.Sum"
          + "maryEntry\0227\n\005state\030\003 \001(\0162(.google.events"
          + ".cloud.apihub.v1.LintState\022\016\n\006source\030\004 \001"
          + "(\t\0225\n\006linter\030\005 \001(\0162%.google.events.cloud"
          + ".apihub.v1.Linter\022/\n\013create_time\030\006 \001(\0132\032"
          + ".google.protobuf.Timestamp\032X\n\014SummaryEnt"
          + "ry\0229\n\010severity\030\001 \001(\0162\'.google.events.clo"
          + "ud.apihub.v1.Severity\022\r\n\005count\030\002 \001(\005\"\244\001\n"
          + "\005Issue\022\014\n\004code\030\001 \001(\t\022\014\n\004path\030\002 \003(\t\022\017\n\007me"
          + "ssage\030\003 \001(\t\0229\n\010severity\030\004 \001(\0162\'.google.e"
          + "vents.cloud.apihub.v1.Severity\0223\n\005range\030"
          + "\005 \001(\0132$.google.events.cloud.apihub.v1.Ra"
          + "nge\"o\n\005Range\0223\n\005start\030\001 \001(\0132$.google.eve"
          + "nts.cloud.apihub.v1.Point\0221\n\003end\030\002 \001(\0132$"
          + ".google.events.cloud.apihub.v1.Point\"(\n\005"
          + "Point\022\014\n\004line\030\001 \001(\005\022\021\n\tcharacter\030\002 \001(\005\"\301"
          + "\004\n\016ApiHubInstance\022\014\n\004name\030\001 \001(\t\022/\n\013creat"
          + "e_time\030\002 \001(\0132\032.google.protobuf.Timestamp"
          + "\022/\n\013update_time\030\003 \001(\0132\032.google.protobuf."
          + "Timestamp\022B\n\005state\030\004 \001(\01623.google.events"
          + ".cloud.apihub.v1.ApiHubInstance.State\022\025\n"
          + "\rstate_message\030\005 \001(\t\022D\n\006config\030\006 \001(\01324.g"
          + "oogle.events.cloud.apihub.v1.ApiHubInsta"
          + "nce.Config\022I\n\006labels\030\007 \003(\01329.google.even"
          + "ts.cloud.apihub.v1.ApiHubInstance.Labels"
          + "Entry\022\023\n\013description\030\010 \001(\t\032\037\n\006Config\022\025\n\r"
          + "cmek_key_name\030\001 \001(\t\032-\n\013LabelsEntry\022\013\n\003ke"
          + "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"n\n\005State\022\025\n\021S"
          + "TATE_UNSPECIFIED\020\000\022\014\n\010INACTIVE\020\001\022\014\n\010CREA"
          + "TING\020\002\022\n\n\006ACTIVE\020\003\022\014\n\010UPDATING\020\004\022\014\n\010DELE"
          + "TING\020\005\022\n\n\006FAILED\020\006\"\302\003\n\013ExternalApi\022\014\n\004na"
          + "me\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t\022\023\n\013descri"
          + "ption\030\003 \001(\t\022\021\n\tendpoints\030\004 \003(\t\022\r\n\005paths\030"
          + "\005 \003(\t\022C\n\rdocumentation\030\006 \001(\0132,.google.ev"
          + "ents.cloud.apihub.v1.Documentation\022N\n\nat"
          + "tributes\030\007 \003(\0132:.google.events.cloud.api"
          + "hub.v1.ExternalApi.AttributesEntry\022/\n\013cr"
          + "eate_time\030\010 \001(\0132\032.google.protobuf.Timest"
          + "amp\022/\n\013update_time\030\t \001(\0132\032.google.protob"
          + "uf.Timestamp\032a\n\017AttributesEntry\022\013\n\003key\030\001"
          + " \001(\t\022=\n\005value\030\002 \001(\0132..google.events.clou"
          + "d.apihub.v1.AttributeValues:\0028\001\"m\n\027HostP"
          + "rojectRegistration\022\014\n\004name\030\001 \001(\t\022\023\n\013gcp_"
          + "project\030\002 \001(\t\022/\n\013create_time\030\003 \001(\0132\032.goo"
          + "gle.protobuf.Timestamp\"r\n\030RuntimeProject"
          + "Attachment\022\014\n\004name\030\001 \001(\t\022\027\n\017runtime_proj"
          + "ect\030\002 \001(\t\022/\n\013create_time\030\003 \001(\0132\032.google."
          + "protobuf.Timestamp\"C\n\014ApiEventData\0223\n\007pa"
          + "yload\030\001 \001(\0132\".google.events.cloud.apihub"
          + ".v1.Api\"K\n\020VersionEventData\0227\n\007payload\030\001"
          + " \001(\0132&.google.events.cloud.apihub.v1.Ver"
          + "sion\"E\n\rSpecEventData\0224\n\007payload\030\001 \001(\0132#"
          + ".google.events.cloud.apihub.v1.Spec\"Q\n\023D"
          + "eploymentEventData\022:\n\007payload\030\001 \001(\0132).go"
          + "ogle.events.cloud.apihub.v1.Deployment\"O"
          + "\n\022AttributeEventData\0229\n\007payload\030\001 \001(\0132(."
          + "google.events.cloud.apihub.v1.Attribute\""
          + "S\n\024ExternalApiEventData\022;\n\007payload\030\001 \001(\013"
          + "2*.google.events.cloud.apihub.v1.Externa"
          + "lApi\"Q\n\023DependencyEventData\022:\n\007payload\030\001"
          + " \001(\0132).google.events.cloud.apihub.v1.Dep"
          + "endency\"k\n HostProjectRegistrationEventD"
          + "ata\022G\n\007payload\030\001 \001(\01326.google.events.clo"
          + "ud.apihub.v1.HostProjectRegistration\"Y\n\027"
          + "ApiHubInstanceEventData\022>\n\007payload\030\001 \001(\013"
          + "2-.google.events.cloud.apihub.v1.ApiHubI"
          + "nstance\"m\n!RuntimeProjectAttachmentEvent"
          + "Data\022H\n\007payload\030\001 \001(\01327.google.events.cl"
          + "oud.apihub.v1.RuntimeProjectAttachment*U"
          + "\n\tLintState\022\032\n\026LINT_STATE_UNSPECIFIED\020\000\022"
          + "\026\n\022LINT_STATE_SUCCESS\020\001\022\024\n\020LINT_STATE_ER"
          + "ROR\020\002*9\n\006Linter\022\026\n\022LINTER_UNSPECIFIED\020\000\022"
          + "\014\n\010SPECTRAL\020\001\022\t\n\005OTHER\020\002*t\n\010Severity\022\030\n\024"
          + "SEVERITY_UNSPECIFIED\020\000\022\022\n\016SEVERITY_ERROR"
          + "\020\001\022\024\n\020SEVERITY_WARNING\020\002\022\021\n\rSEVERITY_INF"
          + "O\020\003\022\021\n\rSEVERITY_HINT\020\004B\222\001\n!com.google.ev"
          + "ents.cloud.apihub.v1P\001\252\002&Google.Events.P"
          + "rotobuf.Cloud.ApiHub.V1\312\002\035Google\\Events\\"
          + "Cloud\\ApiHub\\V1\352\002!Google::Events::Cloud:"
          + ":ApiHub::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_events_cloud_apihub_v1_Api_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Api_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Api_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "Documentation",
              "Owner",
              "Versions",
              "CreateTime",
              "UpdateTime",
              "TargetUser",
              "Team",
              "BusinessUnit",
              "MaturityLevel",
              "Attributes",
              "ApiStyle",
              "SelectedVersion",
            });
    internal_static_google_events_cloud_apihub_v1_Api_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_Api_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Api_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Api_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_Version_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_events_cloud_apihub_v1_Version_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Version_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "Documentation",
              "Specs",
              "ApiOperations",
              "Definitions",
              "Deployments",
              "CreateTime",
              "UpdateTime",
              "Lifecycle",
              "Compliance",
              "Accreditation",
              "Attributes",
              "SelectedDeployment",
            });
    internal_static_google_events_cloud_apihub_v1_Version_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_Version_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Version_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Version_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_Spec_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_events_cloud_apihub_v1_Spec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Spec_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "SpecType",
              "Details",
              "SourceUri",
              "CreateTime",
              "UpdateTime",
              "LintResponse",
              "Attributes",
              "Documentation",
            });
    internal_static_google_events_cloud_apihub_v1_Spec_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_Spec_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Spec_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Spec_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_Deployment_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_events_cloud_apihub_v1_Deployment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Deployment_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "Documentation",
              "DeploymentType",
              "ResourceUri",
              "Endpoints",
              "ApiVersions",
              "CreateTime",
              "UpdateTime",
              "Slo",
              "Environment",
              "Attributes",
            });
    internal_static_google_events_cloud_apihub_v1_Deployment_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_Deployment_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Deployment_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Deployment_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_Attribute_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_events_cloud_apihub_v1_Attribute_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Attribute_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "DefinitionType",
              "Scope",
              "DataType",
              "AllowedValues",
              "Cardinality",
              "Mandatory",
              "CreateTime",
              "UpdateTime",
            });
    internal_static_google_events_cloud_apihub_v1_Attribute_AllowedValue_descriptor =
        internal_static_google_events_cloud_apihub_v1_Attribute_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Attribute_AllowedValue_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Attribute_AllowedValue_descriptor,
            new java.lang.String[] {
              "Id", "DisplayName", "Description", "Immutable",
            });
    internal_static_google_events_cloud_apihub_v1_SpecContents_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_events_cloud_apihub_v1_SpecContents_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_SpecContents_descriptor,
            new java.lang.String[] {
              "Contents", "MimeType",
            });
    internal_static_google_events_cloud_apihub_v1_SpecDetails_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_events_cloud_apihub_v1_SpecDetails_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_SpecDetails_descriptor,
            new java.lang.String[] {
              "OpenApiSpecDetails", "Description", "Details",
            });
    internal_static_google_events_cloud_apihub_v1_OpenApiSpecDetails_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_events_cloud_apihub_v1_OpenApiSpecDetails_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_OpenApiSpecDetails_descriptor,
            new java.lang.String[] {
              "Format", "Version", "Owner",
            });
    internal_static_google_events_cloud_apihub_v1_Owner_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_events_cloud_apihub_v1_Owner_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Owner_descriptor,
            new java.lang.String[] {
              "DisplayName", "Email",
            });
    internal_static_google_events_cloud_apihub_v1_Documentation_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_events_cloud_apihub_v1_Documentation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Documentation_descriptor,
            new java.lang.String[] {
              "ExternalUri",
            });
    internal_static_google_events_cloud_apihub_v1_AttributeValues_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_events_cloud_apihub_v1_AttributeValues_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_AttributeValues_descriptor,
            new java.lang.String[] {
              "EnumValues", "StringValues", "JsonValues", "Attribute", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_AttributeValues_EnumAttributeValues_descriptor =
        internal_static_google_events_cloud_apihub_v1_AttributeValues_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apihub_v1_AttributeValues_EnumAttributeValues_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_AttributeValues_EnumAttributeValues_descriptor,
            new java.lang.String[] {
              "Values",
            });
    internal_static_google_events_cloud_apihub_v1_AttributeValues_StringAttributeValues_descriptor =
        internal_static_google_events_cloud_apihub_v1_AttributeValues_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apihub_v1_AttributeValues_StringAttributeValues_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_AttributeValues_StringAttributeValues_descriptor,
            new java.lang.String[] {
              "Values",
            });
    internal_static_google_events_cloud_apihub_v1_Dependency_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_events_cloud_apihub_v1_Dependency_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Dependency_descriptor,
            new java.lang.String[] {
              "Name",
              "Consumer",
              "Supplier",
              "State",
              "Description",
              "DiscoveryMode",
              "ErrorDetail",
              "CreateTime",
              "UpdateTime",
              "Attributes",
            });
    internal_static_google_events_cloud_apihub_v1_Dependency_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_Dependency_descriptor.getNestedTypes().get(0);
    internal_static_google_events_cloud_apihub_v1_Dependency_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Dependency_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_DependencyEntityReference_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_events_cloud_apihub_v1_DependencyEntityReference_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_DependencyEntityReference_descriptor,
            new java.lang.String[] {
              "OperationResourceName", "ExternalApiResourceName", "DisplayName", "Identifier",
            });
    internal_static_google_events_cloud_apihub_v1_DependencyErrorDetail_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_events_cloud_apihub_v1_DependencyErrorDetail_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_DependencyErrorDetail_descriptor,
            new java.lang.String[] {
              "Error", "ErrorTime",
            });
    internal_static_google_events_cloud_apihub_v1_LintResponse_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_events_cloud_apihub_v1_LintResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_LintResponse_descriptor,
            new java.lang.String[] {
              "Issues", "Summary", "State", "Source", "Linter", "CreateTime",
            });
    internal_static_google_events_cloud_apihub_v1_LintResponse_SummaryEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_LintResponse_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apihub_v1_LintResponse_SummaryEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_LintResponse_SummaryEntry_descriptor,
            new java.lang.String[] {
              "Severity", "Count",
            });
    internal_static_google_events_cloud_apihub_v1_Issue_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_events_cloud_apihub_v1_Issue_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Issue_descriptor,
            new java.lang.String[] {
              "Code", "Path", "Message", "Severity", "Range",
            });
    internal_static_google_events_cloud_apihub_v1_Range_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_events_cloud_apihub_v1_Range_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Range_descriptor,
            new java.lang.String[] {
              "Start", "End",
            });
    internal_static_google_events_cloud_apihub_v1_Point_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_events_cloud_apihub_v1_Point_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_Point_descriptor,
            new java.lang.String[] {
              "Line", "Character",
            });
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ApiHubInstance_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "State",
              "StateMessage",
              "Config",
              "Labels",
              "Description",
            });
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_Config_descriptor =
        internal_static_google_events_cloud_apihub_v1_ApiHubInstance_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_Config_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ApiHubInstance_Config_descriptor,
            new java.lang.String[] {
              "CmekKeyName",
            });
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_LabelsEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_ApiHubInstance_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_events_cloud_apihub_v1_ApiHubInstance_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ApiHubInstance_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_ExternalApi_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_events_cloud_apihub_v1_ExternalApi_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ExternalApi_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "Description",
              "Endpoints",
              "Paths",
              "Documentation",
              "Attributes",
              "CreateTime",
              "UpdateTime",
            });
    internal_static_google_events_cloud_apihub_v1_ExternalApi_AttributesEntry_descriptor =
        internal_static_google_events_cloud_apihub_v1_ExternalApi_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_events_cloud_apihub_v1_ExternalApi_AttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ExternalApi_AttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_events_cloud_apihub_v1_HostProjectRegistration_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_events_cloud_apihub_v1_HostProjectRegistration_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_HostProjectRegistration_descriptor,
            new java.lang.String[] {
              "Name", "GcpProject", "CreateTime",
            });
    internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachment_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachment_descriptor,
            new java.lang.String[] {
              "Name", "RuntimeProject", "CreateTime",
            });
    internal_static_google_events_cloud_apihub_v1_ApiEventData_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_events_cloud_apihub_v1_ApiEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ApiEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_VersionEventData_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_events_cloud_apihub_v1_VersionEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_VersionEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_SpecEventData_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_events_cloud_apihub_v1_SpecEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_SpecEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_DeploymentEventData_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_events_cloud_apihub_v1_DeploymentEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_DeploymentEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_AttributeEventData_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_events_cloud_apihub_v1_AttributeEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_AttributeEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_ExternalApiEventData_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_events_cloud_apihub_v1_ExternalApiEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ExternalApiEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_DependencyEventData_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_events_cloud_apihub_v1_DependencyEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_DependencyEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_HostProjectRegistrationEventData_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_events_cloud_apihub_v1_HostProjectRegistrationEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_HostProjectRegistrationEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_ApiHubInstanceEventData_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_events_cloud_apihub_v1_ApiHubInstanceEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_ApiHubInstanceEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachmentEventData_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachmentEventData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_events_cloud_apihub_v1_RuntimeProjectAttachmentEventData_descriptor,
            new java.lang.String[] {
              "Payload",
            });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
